default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: timeclock_development

test:
  <<: *default
  database: timeclock_test

production:
  <<: *default
  database: timeclock_production
  username: timeclock
  password: timeclock_2014
